{{- if .Values.eksCluster }}
apiVersion: apps/v1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Deployment
metadata:
  name: {{ .Values.service.name }}
  labels:
    chart: "{{ .Chart.Name | trunc 63 }}"
    chartVersion: "{{ .Chart.Version | trunc 63 }}"
    visualize: "true"
    app: {{ .Values.service.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  template:
    metadata:
 {{- with .Values.annotations }}
      annotations:
 {{ toYaml . | indent 8 }}
 {{- end }}
      labels:
        app: {{ .Values.service.name }}
        visualize: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ .Values.service.name }}
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Chart.Version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: WORKERS
          value: "{{ .Values.env.WORKERS }}"
        - name: CHAN_BUFFER
          value: "{{ .Values.env.CHAN_BUFFER }}"
        - name: BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: splunk.forwarder.s3.bucket
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: splunk.forwarder.aws.region
        - name: ENV
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: environment
        - name: FORWARD_URL
          valueFrom:
            secretKeyRef:
              name: splunk-forwarder
              key: hec.url
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: splunk-forwarder
              key: hec.token
        ports:
        - containerPort: 8080
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: "/__gtg"
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 30
        resources:
{{ toYaml .Values.resources | indent 12 }}

